### ISSUE TITLE
Video Slides

### ISSUE THREAD

**Issue by marshalls** [RiseLedger/Nex#2]
Is there a way to make the 'delay' property work with video slides?  We are trying to show live YouTube feeds and need them to automatically slide to the next video after the 'delay'.

**Comment by RiseLedger** [comment]
There is only a delay option between the slides switches. If it is ok for you, then can use it. Something like this:

```
new Nex({
    delay  : 7000, //  7 seconds delay between images or video switches
});
```

At the moment you can not make a delay bigger for individual slide, delay will be applied for all slides.
Another option will be to set **autoplay** to false and the slide will never change.

**Comment by marshalls** [comment]
Correct, but what I have found is that the delay option does not affect video slides, the first video plays forever and does not automatically change to the next video.  Clicking on the bullets will change the video but it will not automatically change.

Here is my code:
jQuery(function() {

```
    new Nex({
            transition       : "random", // none || fade || slideLeft || slideRight || slideTop || slideBottom || zoom || rotate || skew || random
            transition_speed : 600, // how long the transition between two images will durate
            delay            : 7000, // between images transition
            autoplay         : true, // true || false
            thumbnails       : true, // true || false
            bullets          : true,  // true || false
            bar              : true, // true || false
            load_bar         : true, // true || false
            data             : [
                    {
                            display     : "image", // image, map, video
                            url         : "https://www.youtube.com/v/PrutDmA0AkE&vq=hd720", // video link
                            title       : "Yuma",
                            description : " &mdash; Embed Videos from Youtube",
                            thumb       : "../../../images/thumb_video_mm.jpg"
                    },
                    {
                            display     : "video", // image, map, video
                            url         : "https://www.youtube.com/v/LTV9pTazQLM&vq=hd720", // video link
                            title       : "Limon",
                            description : " &mdash; Use HTML in the Description",
                            thumb       : "../../../images/thumb_video_vs.jpg"
                    }
            ]
    });
```

});

**Comment by marshalls** [comment]
Even in your example showing videos, when you set autoplay to 'true' and add a delay, the videos do not automatically change.

**Comment by RiseLedger** [comment]
Yes you are right. Actually If the slide is video I disable the autoplay. Do you think I should remove this and anyway go to next slide or do you have a better idea of how to handle the situations with videos?

Obviously to change the slide after 7 seconds is not a solution.

**Comment by marshalls** [comment]
In my case, we actually do want to change the slide every "x" number of seconds as we are wanting to show a bunch of live feeds on a big display in our office.  So we want to automatically change to the next video by using the delay.

**Comment by RiseLedger** [comment]
Like a dirty and temporary solution you can remove the line that disable the autoplay from the Nex.js file. Take a look at line 701 and there remove this code:

```
if(nex.opt.autoplay)
    nex.isAutoplay = false;
```

This should fix the problem for you.

A better approach of course will be to implement the slide to change when the video is ending, I think of it to add at the next releases.

**Comment by marshalls** [comment]
## That worked perfectly. Thanks for the help and for the awesome plugin! 

## 

 Steven Marshall 

On 2015-04-16 14:12, Rise Ledger wrote: 

> Like a dirty and temporary solution you can remove the line that disable the autoplay from the Nex.js file. Take a look at line 701 and there remove this code: 
> 
> if(nex.opt.autoplay)
> nex.isAutoplay = false;
> 
> This should fix the problem for you. 
> 
> A better approach of course will be to implement the slide to change when the video is changing, I think of it to add at the next releases. 
> 
> ## 
> 
> Reply to this email directly or view it on GitHub [1].

## Links:

[1] https://github.com/RiseLedger/Nex/issues/2#issuecomment-93829016
