### ISSUE TITLE
encapsulating the slider HTML code in a DIV

### ISSUE THREAD

**Issue by jayantdash** [RiseLedger/Nex#5]
Hi,
I found this slider is awesome. thanks for sharing.

As I am new to web development facing some issues while integrating this slider in my website.
can we encapsulate the slider HTML code in a specific DIV, currently its appending to BODY.
my requirement is to add fixed nav above and content below the slider.

Really appreciate if one example can be added to this repo.
Adv thanks.

**Comment by RiseLedger** [comment]
Hi,
Actually if you will check the source code of html page you will see that the slider is encapsulated in #nex div , and this div is appended at the end to body tag.

Let me know how you will want everything to be, and will be more easier for you to obtain the desired result.
Thanks

**Comment by jayantdash** [comment]
Hi,
many thanks for you quick response.
I managed this by changing jQuery("body") to jQuery("my-slider") DIV  wanted to encapsulate the slider within.

Is what I am doing is correct.

below is what I am trying to do



```
 <div id="my-top-header">
         <!-- top header goes here-->
 </div>
  <div id="my-slider">
         <!-- nex slider goes here-->
  </div>
  <div id="my-content">
         <!-- contentr goes here-->
  </div>
```

</body>

Thanks

**Comment by RiseLedger** [comment]
Great, yes it is also a solution what you have made.

Thanks

**Comment by jayantdash** [comment]
Thanks,
Please let me know if any better solution is there without editing the source nex.js file
